# Generated by Django 6.0.3 on 2026-04-07 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'recipe')},
        ),
    ]
