# Generated by Django 6.0.3 on 2026-04-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
